# Generated by Django 3.2 on 2021-05-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='joboffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('date_posted', models.CharField(max_length=250)),
                ('job_link', models.TextField()),
            ],
        ),
    ]
